### ISSUE TITLE
Hi from Platts (SPGCI)

### ISSUE THREAD

**Issue by achristie** [aeorxc/pyplattsapi#1]
Hello @aeorxc ,

I came across this project and wanted to reach out to see if you'd be interested in trying out a new python package we're in the early stages of developing.

[Python Package](https://pypi.org/project/spgci/)

some of the features are listed but I'll highlight a few:
1) Data is returned as a DataFrame. Types are automatically set for the Date fields.
2) Easily construct filter expressions using native python types (strings, lists, pd.Series)
3) Auto paginate the data if the response spans more than 1 page and concatenate into a single DataFrame

Feel free to reach out to me directly if you're interested.
Andrew Christie / andrew.christie@spglobal.com

**Comment by aeorxc** [comment]
Hi Andrew

Thanks for bringing this to my attention. We primarily get market/price data from Morningstar (it provides a consistent access point for all prices from Argus/Platts/ICE/OPIS etc.

Will you be expanding your package to the fundamentals side of the API? We would definitely be interested in a wrapper for the world refinery database/ oil supply side of things.

Thanks

**Comment by achristie** [comment]
In the process of adding World Oil Supply. 

What types of queries do you run against WRD?

**Comment by aeorxc** [comment]
Ideally we would want support for all the endpoint available but as a starting point we have been trying to pull capacity and run series - at a refinery / country region level.

See the example in the test file here for an idea:
https://github.com/aeorxc/pyplattsapi/blob/main/tests/test_world_refinery_database.py

**Comment by achristie** [comment]
@aeorxc we have added WOS and WRD. 

This is preview software still but you're welcome to take a look and give any feedback. It doesn't take advantage of all oDATA features and we didn't all all reference data endpoints (yet).
